var dadosAlunos =
[
    {
        "carimboDeDatahora": 42970.42636924768,
        "endereoDeEmail": "gabrielpresotocel@gmail.com",
        "nome": "gabriel rocha Presoto",
        "ra": 1090481711039,
        "idade": "8/17/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.58748659722,
        "endereoDeEmail": "siqueirabruno3@gmail.com",
        "nome": "Bruno Assis Siqueira",
        "ra": 1090481711005,
        "idade": "4/19/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.6172202662,
        "endereoDeEmail": "felipergsouza@gmail.com",
        "nome": "Felipe Ramos Gonçalves de Souza",
        "ra": 1090481623012,
        "idade": "2/24/1988",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.61795489583,
        "endereoDeEmail": "deisegrisi@hotmail.com",
        "nome": "Deise Grisi Barbosa",
        "ra": 1090481713004,
        "idade": "7/4/1994",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.62987484953,
        "endereoDeEmail": "lucasaassis@outlook.com",
        "nome": "Lucas Fernando de Assis",
        "ra": 1090481711022,
        "idade": "8/7/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Financiado",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 1,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.6316837037,
        "endereoDeEmail": "joaovitor_02@outlook.com",
        "nome": "João Vítor de Lima Valim",
        "ra": 1090481713016,
        "idade": "6/2/1997",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.65118688658,
        "endereoDeEmail": "f.barichello@bol.com.br",
        "nome": "Fúlvio Belato de Freitas Barichello",
        "ra": 1090481713008,
        "idade": "10/15/1992",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Maior parte em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.662592187495,
        "endereoDeEmail": "brunooliveiraeoliveira@outlook.com",
        "nome": "Bruno Oliveira e Oliveira ",
        "ra": 1090481713002,
        "idade": "10/17/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Região de Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.67198353009,
        "endereoDeEmail": "karol.fradique@gmail.com",
        "nome": "Karoliny Fradique Bassi",
        "ra": 1090481613019,
        "idade": "8/17/1996",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.678679351855,
        "endereoDeEmail": "phcs010@gmail.com",
        "nome": "Pedro Henrique Cunha dos Santos ",
        "ra": 1090481713028,
        "idade": "4/18/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Maior parte em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Básico",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Sem opção de \"desempregado \""
    },
    {
        "carimboDeDatahora": 42969.68906780092,
        "endereoDeEmail": "joylsont@gmail.com",
        "nome": "Joylson Tavares Miranda",
        "ra": 1090481713018,
        "idade": "11/11/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.70704108797,
        "endereoDeEmail": "gustavo-teixeira2011@hotmail.com",
        "nome": "Gustavo Rodrigues Teixeira",
        "ra": 1090481711038,
        "idade": "5/30/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Pode mudar a forma de informar a data de nascimento"
    },
    {
        "carimboDeDatahora": 42969.713294456014,
        "endereoDeEmail": "vitorhscampos@gmail.com",
        "nome": "Vitor Hugo Souza de Campos",
        "ra": 1090481713037,
        "idade": "4/6/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Andando",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": 2,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Outro",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42969.73750565972,
        "endereoDeEmail": "ja.trevizani@hotmail.com",
        "nome": "João Arthur Coelho Trevizani",
        "ra": 1090481711017,
        "idade": "2/12/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Quando pergunta a renda de todos da casa não tem lá explicando q são salários mínimos."
    },
    {
        "carimboDeDatahora": 42970.34728023148,
        "endereoDeEmail": "matheusrodrigues_912@hotmail.com",
        "nome": "Matheus Rodrigues",
        "ra": 1090481711023,
        "idade": "12/9/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.407396828705,
        "endereoDeEmail": "eu@meu.email",
        "nome": "Teste",
        "ra": 1090481711044,
        "idade": "11/12/2017",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Casado(a)",
        "filhos": 3,
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Maior parte em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Outro",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.41354207176,
        "endereoDeEmail": "bia_oliveira17@outlook.com.br",
        "nome": "Beatriz Fernanda Koreias Oliveira",
        "ra": 1090481711004,
        "idade": "5/17/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": 1,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 1,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Básico",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.414752303244,
        "endereoDeEmail": "clebermourajr@gmail.com",
        "nome": "cleber jose de moura junior",
        "ra": 1090481711044,
        "idade": "6/27/1989",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Casado(a)",
        "filhos": 1,
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Financiado",
        "tempoDeMoradiaanos": 3,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.41915155093,
        "endereoDeEmail": "carlosdk45@hotmail.com",
        "nome": "Carlos Augusto",
        "ra": 1090481711032,
        "idade": "9/3/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Maior parte em Escola Particular",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.42140348379,
        "endereoDeEmail": "mlopesandrade@gmail.com",
        "nome": "Murilo Lopes Andrade",
        "ra": 1090481611030,
        "idade": "1/11/1986",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": 1,
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": 2,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Não vi nada errado. Obrigado."
    },
    {
        "carimboDeDatahora": 42970.4226527662,
        "endereoDeEmail": "leonardoolitrabson@gmail.com",
        "nome": "Leonardo Xavier de Oliveira",
        "ra": 1090481711019,
        "idade": "7/13/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.424043252315,
        "endereoDeEmail": "Leonnisvieira@hotmail.com",
        "nome": "Leonnis",
        "ra": 1090481711020,
        "idade": "10/19/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.42451724537,
        "endereoDeEmail": "gportelada@outlook.com",
        "nome": "Gabriel Cavalcanti Fernandes Portelada",
        "ra": 1090481721013,
        "idade": "3/15/1991",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Particular",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Não"
    },
    {
        "carimboDeDatahora": 42970.42742921296,
        "endereoDeEmail": "daniel.730@outlook.com",
        "nome": "Daniel Pereira da Silva",
        "ra": 1090481711007,
        "idade": "7/6/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Região de Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.42799532408,
        "endereoDeEmail": "vitor.padilha@mail.ru",
        "nome": "vitor eduardo dos santos padilha",
        "ra": 1090481711030,
        "idade": "12/28/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Outro",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol, Outros",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.427996805556,
        "endereoDeEmail": "Flavinha_limeira@hotmail.com",
        "nome": "Ana Flávia Limeira",
        "ra": 1090481711001,
        "idade": "5/19/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Bicicleta",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Não. Já trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 1,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "No período em que exerce a atividade remunerada, colocar opção para quem não a exerce."
    },
    {
        "carimboDeDatahora": 42970.43002681713,
        "endereoDeEmail": "gabrielsilvamelo22@hotmail.com",
        "nome": "Gabriel Silva Melo",
        "ra": 1090481711014,
        "idade": "7/16/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Andando",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Básico",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.43145837963,
        "endereoDeEmail": "vitor20101983@gmail.com",
        "nome": "Vitor Reis Silva e Sousa",
        "ra": 1090481711033,
        "idade": "6/15/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.49370511574,
        "endereoDeEmail": "ovatsugdasilvagomes@Hotmail.com",
        "nome": "Gustavo da Silva Gomes ",
        "ra": 1090481713014,
        "idade": "5/7/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.51985254629,
        "endereoDeEmail": "entradaproibid@hotmail.com",
        "nome": "Vinícius Alves da Silva",
        "ra": 1090481621032,
        "idade": "11/13/1991",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Sozinho",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "qualAMediaDaSuaRendaEmSalriosMnimos": 2,
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.60731603009,
        "endereoDeEmail": "alineaparecidacintrasilva@gmail.com",
        "nome": "Aline Aparecida Cintra Silva",
        "ra": 1090481713040,
        "idade": "5/20/1992",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Outro",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Financiado",
        "tempoDeMoradiaanos": 1,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Básico",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "em ''com quem mora'' não tinha companheiro/marido. Moro com meu namorado, mas coloquei família, porque não tinha opção. "
    },
    {
        "carimboDeDatahora": 42971.30658880787,
        "endereoDeEmail": "gabrielribeiro1698@gmail.com",
        "nome": "Gabriel Antonio Ribeiro",
        "ra": 1090481713009,
        "idade": "10/17/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.34413704861,
        "endereoDeEmail": "luizgrespi@hotmail.com",
        "nome": "Luiz Guilherme Grespi Oliveira",
        "ra": 1090481611028,
        "idade": "10/16/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde, Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.540662245374,
        "endereoDeEmail": "sthanleyy@hotmail.com",
        "nome": "Sthanley Zani Damando Soares",
        "ra": 1090481713039,
        "idade": "4/16/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.60949125,
        "endereoDeEmail": "larissakeller@live.com",
        "nome": "Larissa Keller de Souza Gonçalves",
        "ra": 1090481713020,
        "idade": "6/22/1998",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.650965775465,
        "endereoDeEmail": "gustavo.a.felicio@gmail.com",
        "nome": "Gustavo Felício",
        "ra": 1090481613019,
        "idade": "7/2/1990",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 1,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.722634907404,
        "endereoDeEmail": "jhonny_will2@hotmail.com",
        "nome": "Jhonatan Willian Gonçalves",
        "ra": 1090481713015,
        "idade": "6/16/1997",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Não. Nunca trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.79165917824,
        "endereoDeEmail": "gabrielferrer@outlook.com.br",
        "nome": "Gabriel de Paula Ferreira",
        "ra": 1090481713011,
        "idade": "7/8/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.81924936343,
        "endereoDeEmail": "felipefaraujo14@gmail.com",
        "nome": "felipe faria de araujo",
        "ra": 1090481621008,
        "idade": "7/3/1997",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 2,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês, Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.82211329861,
        "endereoDeEmail": "eliabnerpereira@outlook.com",
        "nome": "Eliabner Pereira Pinto",
        "ra": 1090481711010,
        "idade": "7/24/1989",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Casado(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Financiado",
        "tempoDeMoradiaanos": 3,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 2,
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.82654185186,
        "endereoDeEmail": "gabrielcarvalhocosta@live.com",
        "nome": "Gabriel Carvalho",
        "ra": 1090481713010,
        "idade": "1/21/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 2,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "ta tudo errado parça, a pergunta da renda n especifica a unidade de medida, e a idade n é idade na verdade, é a data de nascimento, não a idade, se n, seria a idade, mas como n é, é a data de nascimento, só que esta escrito idade, mas não é idade."
    },
    {
        "carimboDeDatahora": 42971.8266741088,
        "endereoDeEmail": "marcel.garcia.franca@hotmail.com",
        "nome": "Marcel Garcia França",
        "ra": 1090481713023,
        "idade": "10/23/1987",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": 1,
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Andando",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": 1,
        "comQuemMora": "Republica",
        "quantasPessoasResidemComVocIncluindoVoc": 1,
        "exerceAtividadeRemunerada": "Não. Já trabalhei na área do curso.",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 1,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Para obter alguma certificação",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "APP",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Não"
    },
    {
        "carimboDeDatahora": 42971.83266579861,
        "endereoDeEmail": "ovatsugdasilvagomes@hotmail.com",
        "nome": "Gustavo da Silva Gomes",
        "ra": 1090481713014,
        "idade": "5/7/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Ônibus",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "4 ou mais",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.83366988426,
        "endereoDeEmail": "carolinasilva.adm@gmail.com",
        "nome": "Ana Carolina Silva",
        "ra": 1090481713001,
        "idade": "10/12/1989",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": 2,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Experiência Profissional",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "Algumas perguntas foram formuladas de maneira 'estranha'"
    },
    {
        "carimboDeDatahora": 42971.83535685185,
        "endereoDeEmail": "danielmcs18@gmail.com",
        "nome": "Daniel Mendes de Castro",
        "ra": 1090481713004,
        "idade": "6/13/1997",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Outro",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.839046863424,
        "endereoDeEmail": "heron.peixoto3@gmail.com",
        "nome": "Luis Heron de Souza Peixoto",
        "ra": 1090481723025,
        "idade": "5/16/1989",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Financiado",
        "tempoDeMoradiaanos": 1,
        "comQuemMora": "Sozinho",
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "qualAMediaDaSuaRendaEmSalriosMnimos": 2,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42971.8456002662,
        "endereoDeEmail": "matheusf_francisco@hotmail.com",
        "nome": "Matheus Ferreira Francisco",
        "ra": 1090481713025,
        "idade": "8/22/1994",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": 3,
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 1,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": 3,
        "periodo": "Noturno",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoNoturnoEmQualPerodoExerceAtividadeRemunerada": "Manhã, Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Avançado",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Para obter alguma certificação",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web",
        "viuAlgoDeErradoTemAlgumaDicaEscrevaAbaixo": "\"Incluindo você, qual a soma da renda das pessoas que residem com você\"? Poderia ser incluido nas opções de resposta por exemplo \"1 Salario Mínimo, 2 Salarios Mínimos...\" pois não fica dificil interpretar e responder."
    },
    {
        "carimboDeDatahora": 42971.850477175925,
        "endereoDeEmail": "rscheffeld@gmail.com",
        "nome": "Roger Andretto Scheffeld",
        "ra": 1090481521042,
        "idade": "5/9/1996",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": 1,
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Sim. Trabalho na área do curso",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": 3,
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "4 ou mais",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Maior parte em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    },
    {
        "carimboDeDatahora": 42970.41371527778,
        "endereoDeEmail": "mveleuteriodesousa@gmail.com",
        "nome": "Micheli Vanessa Eleuterio de Sousa",
        "ra": "1090481711024",
        "idade": "08/12/1989",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Moto",
        "situaoDomiciliar": "Alugado",
        "tempoDeMoradiaanos": "3",
        "comQuemMora": "Sozinho",
        "exerceAtividadeRemunerada": "Sim. Trabalho fora da área do curso",
        "qualAMediaDaSuaRendaEmSalriosMnimos": "3",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Tarde",
        "suaVidaEscolarFoi": "Integralmente em Escola Pública",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Interesse na Área",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Não"
    },
    {
        "carimboDeDatahora": 42970.414293981485,
        "endereoDeEmail": "pablocarloni@hotmail.com",
        "nome": "Pablo Ramon Carloni",
        "ra": "1090481711027",
        "idade": "14/05/1999",
        "vocTemAlgumaDeficinciafsicamental": "Não",
        "estadoCivil": "Solteiro(a)",
        "filhos": "Não tem filhos",
        "cidadeEmQueReside": "Franca",
        "meioDeLocomoo": "Carro",
        "situaoDomiciliar": "Próprio",
        "tempoDeMoradiaanos": "4 ou mais",
        "comQuemMora": "Família",
        "quantasPessoasResidemComVocIncluindoVoc": "4 ou mais",
        "exerceAtividadeRemunerada": "Nunca trabalhei",
        "incluindoVocQuantasPessoasDaSuaResidenciaExercemAtividadeRemunerada": "2",
        "incluindoVocQualASomaDaRendaDasPessoasQueResidemComVoc": "3",
        "periodo": "Matutino",
        "comoVocRespondeuNaPerguntaAcimaQueEstudaNoPeriodoMatutinoEmQualPerodoExerceAtividadeRemunerada": "Noite",
        "suaVidaEscolarFoi": "Integralmente em Escola Particular",
        "temAlgumConhecimentoEmInformtica": "Intermediario",
        "porQualaisMotivosAbaixoResolveuPrestarVestibularParaFatecFranca": "Gratuidade",
        "temConhecimentoSobreAlgumaLnguaEstrangeira": "Sim",
        "qualisLnguas": "Inglês , Espanhol",
        "paraResponderAEsseQuestionrioQualMeioUsou": "Web"
    }
]

//JSON

//TAMANHO DA TELA
var larguraDaJanela = window.innerWidth;
var AlturaDaJanela = window.innerHeight;
var quantidadeScroll = larguraDaJanela / 2;

window.addEventListener('resize', function(){
    larguraDaJanela = window.innerWidth;
    AlturaDaJanela = window.innerHeight;

    console.log(larguraDaJanela);

    quantidadeScroll = larguraDaJanela / 2;
    console.log(quantidadeScroll)
});

var contadorSlide = 0;

//
var menorDe20 = 0
var ate30 = 0
var ate40 = 0
var maior40 = 0

//ESTADO CIVIL
  var solteiro = 0;
  var casado = 0;
  var outro = 0;





function mostraDados() {
  // console.log(dadosAlunos);
  for(var i=0; i < dadosAlunos.length; i++) {
    document.write(dadosAlunos[i].nome + '<br>') ;
  }
}

function trataDataDeNascimento() {
  var d = new Date();
  var anoAtual = d.getFullYear();
  var mesAtual = d.getMonth() + 1;
  var diaAtual = d.getDate();

  for(var i=0; i < dadosAlunos.length; i++) {
      var data = dadosAlunos[i].idade.split('/');

      //MENOR DE 20
         if(data[2] > 1997 || data[2] == 1997 && data[1] < mesAtual ||
           data[2] == 1997 && data[1] == mesAtual && data[0] < diaAtual) {
            //  console.log("Menor de 20")
             menorDe20++;
         }
      //DE 21 Á 30
         else if (
           data[2] == 1997 && data[1] > mesAtual ||
           data[2] == 1997 && data[1] == mesAtual && data[0] >= diaAtual ||

           data[2] > 1987 || data[2] == 1987 && data[1] < mesAtual ||
           data[2] == 1987 && data[1] == mesAtual && data[0] < diaAtual
         ) {
            //  console.log("Entre 21 a 30");
             ate30++;
         }
      //DE 31 Á 40
         else if (
           data[2] == 1987 && data[1] > mesAtual ||
           data[2] == 1987 && data[1] == mesAtual && data[0] >= diaAtual ||

           data[2] > 1977 || data[2] == 1977 && data[1] < mesAtual ||
           data[2] == 1977 && data[1] == mesAtual && data[0] < diaAtual
         ) {
            //  console.log("Entre 31 a 40");
             ate40++;
         }
         else if (
           data[2] < 1977 ||
           data[2] == 1977 && data[1] > mesAtual ||
           data[2] == 1977 && data[1] == mesAtual && data[0] >= diaAtual
         ) {
          //  console.log("Maior de 40")
           maior40++
         }

  }
  console.log("Menor de 20: "+menorDe20)
  console.log("De 21 á 30: "+ate30)
  console.log("De 31 á 40: "+ate40)
  console.log("Maior que 40: "+maior40)

  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);


  function drawChart() {

    var data = google.visualization.arrayToDataTable([
      ['Idade', 'Quantidade'],
      ['Menos de 20 anos',     menorDe20],
      ['Entre 21 e 30 anos',      ate30],
      ['Entre 31 e 40 anos',      ate40],
      ['Maior de 40 anos',      maior40],

    ]);

    var options = {
      title: 'Idades'
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
  }
}

function tratamentoEstadoCivil() {
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart2);


  for(var i=0; i < dadosAlunos.length; i++) {


    if(dadosAlunos[i].estadoCivil == "Solteiro(a)") {
      solteiro++;
    } else if (dadosAlunos[i].estadoCivil == "Casado(a)") {
      casado++;
    } else {
      outro++;
    }
  }
  function drawChart2() {

    var data = google.visualization.arrayToDataTable([
      ['Estado Civil', 'Situação'],
      ['Solteiro',     solteiro],
      ['Casado',      casado],
      ['Outro',      outro],

    ]);

    var options = {
      title: 'Estado Civil'
    };

    var chart2 = new google.visualization.PieChart(document.getElementById('piechart2'));

    chart2.draw(data, options);
  }
}


function next() {
  todosGraficos = document.querySelectorAll('.grafico');
  if(todosGraficos[contadorSlide + 1] && todosGraficos[contadorSlide + 2] ) {
    console.log("Entrou")
    contadorSlide++;
    console.log(todosGraficos[contadorSlide -1]);
    console.log(todosGraficos[contadorSlide]);

    todosGraficos[contadorSlide - 1].style = "transition: all 2s ease; transform: translateX("+(-quantidadeScroll)+"px)";
    todosGraficos[contadorSlide].style = "transition: all 2s ease; transform: translateX("+(-quantidadeScroll)+"px)";
  }
}

function prev() {
  todosGraficos = document.querySelectorAll('.grafico');
  if(todosGraficos[contadorSlide - 1] && todosGraficos[contadorSlide]) {
    contadorSlide--;
    console.log(todosGraficos[contadorSlide + 1]);
    console.log(todosGraficos[contadorSlide]);
    todosGraficos[contadorSlide + 1].style = "transition: all 2s ease; transform: translateX("+quantidadeScroll+"px)";
    todosGraficos[contadorSlide].style = "transition: all 2s ease; transform: translateX("+0+"px)";
  }
}
